"""UI level on taxonomies

Revision ID: 14ff8c47a820
Revises: 47f58d1fe494
Create Date: 2024-05-21 10:44:49.975791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14ff8c47a820"
down_revision: Union[str, None] = "47f58d1fe494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("taxonomies", sa.Column("ui_level", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("taxonomies", "ui_level")
    # ### end Alembic commands ###
