"""Removing unique constraint on parameter names

Revision ID: 7947fad92eea
Revises: 000f49021d44
Create Date: 2024-09-05 08:22:26.775973

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7947fad92eea"
down_revision: Union[str, None] = "000f49021d44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_parameters_name", table_name="parameters")
    op.create_index(op.f("ix_parameters_name"), "parameters", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_parameters_name"), table_name="parameters")
    op.create_index("ix_parameters_name", "parameters", ["name"], unique=1)
    # ### end Alembic commands ###
