"""Parameters fixed at 'disabled'

Revision ID: b0a667f15e4f
Revises: f54b9982ea80
Create Date: 2024-09-30 10:46:24.670633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0a667f15e4f"
down_revision: Union[str, None] = "f54b9982ea80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parameters", sa.Column("disabled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parameters", "disabled")
    # ### end Alembic commands ###
